sonar.projectKey=Kyosuke01_EducPro
sonar.organization=kyosuke01
sonar.projectName=EducPro
sonar.projectVersion=1.0
sonar.sources=backend,frontend
sonar.exclusions=**/static/assets/js/lib/**,**/static/assets/css/lib/**,**/__pycache__/**
sonar.python.version=3.12